import Head from 'next/head'
import Drawer from './components/Drawer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React-TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    	<h1 className="title">Home</h1>
      <p>
        Please click on Projects button on the side bar.
      </p>
    </div>
  )
}

Home.getLayout = function getLayout(page: any) {
  return (
    <Drawer>
      {page}
    </Drawer>
  )
}
